### ISSUE TITLE
undefined method `load_all_lazy_relationships' for nil:NilClass

### ISSUE THREAD

**Issue by cmunozgar** [Bajena/ams_lazy_relationships#30]
Hi there!

What a wonderful gem! Thanks for the great work and for sharing this. It really improves the database performance when removing a lot of N+1 queries. I have set everything in my controller and custom serializer but when running my specs I encounter the following error:

`undefined method `load_all_lazy_relationships' for nil:NilClass`

My custom serializer is called `MemberListSerializer` and is rendering `User` Model Class objects.

Am I missing something? Are custom serializers allowed?

**Comment by Bajena** [comment]
Hey, it'd be best if you posted your exact serializer & test code. If that's not possible then maybe we'll manage to invent something else :D

**Comment by cmunozgar** [comment]
How about if I can screen share with you the problem? Otherwise it would super complicated to replicate the error

**Comment by cmunozgar** [comment]
I'm closing this because it is not happening anymore. I guess I was not setting correctly the serializers and or the loaders.

**Comment by andrewdang17** [comment]
> I'm closing this because it is not happening anymore. I guess I was not setting correctly the serializers and or the loaders.

how did you set it up? I am running into the same issue with a custom serializer

**Comment by cmunozgar** [comment]
I ended up using this sentence inside my custom serializer called `
MemberListSerializer` which renders a `
User` model:

 `lazy_has_many :job_functions, serializer: JobFunctionSerializer, loader: AmsLazyRelationships::Loaders::Association.new('User', :job_functions)` 

Does this help?

**Comment by Bajena** [comment]
Hey @andrewdang17 does it happen when your association evaluates to `nil`?

Maybe you can try this pattern and let me know if it helps?
```ruby
  lazy_has_one :creator, serializer: UserSerializer do |serializer|
    serializer.lazy_creator.itself
  end
```

**Comment by stokarenko** [comment]
@andrewdang17 PR above is fixing the issue, at least for me )
