### ISSUE TITLE
NameError: uninitialized constant ActiveModel::Serializer::Reflection

### ISSUE THREAD

**Issue by pramodshinde** [Bajena/ams_lazy_relationships#59]
Please help me with the issue, I'm missing something?

Added following gems, bundle ran smoothly 

```
active_model_serializers 0.9.3
batch-loader 1.5.0
ams_lazy_relationships 0.3.0
```
On running rake middlewares or rails c getting following error, 

rake aborted!
NameError: uninitialized constant ActiveModel::Serializer::Reflection
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/ams_lazy_relationships-0.3.0/lib/ams_lazy_relationships/extensions/reflection.rb:71:in `<top (required)>'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/ams_lazy_relationships-0.3.0/lib/ams_lazy_relationships/extensions.rb:3:in `<top (required)>'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/ams_lazy_relationships-0.3.0/lib/ams_lazy_relationships.rb:7:in `<top (required)>'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
/Users/pramod/projects/tpn/bullet_api/config/application.rb:20:in `<top (required)>'
/Users/pramod/projects/tpn/bullet_api/Rakefile:4:in `require'
/Users/pramod/projects/tpn/bullet_api/Rakefile:4:in `<top (required)>'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/bin/ruby_executable_hooks:24:in `eval'
/Users/pramod/.rvm/gems/ruby-2.6.6@my_project/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)

**Comment by stokarenko** [comment]
Hi @pramodshinde )

try to use `active_model_serializers ~> 0.10`, should be working )
we need to add this condition to gemspec I guess, @Bajena is it ok to you? )

**Comment by pramodshinde** [comment]
@stokarenko Thanks for the response. 

Is it not supported with `active_model_serializers 0.9.X`? Unfortunately I am on AMS 0.9.x upgrading to 0.10 is major activity.

**Comment by stokarenko** [comment]
@pramodshinde yeah we are forced to patch `ActiveModel::Serializer::Reflection` which comes into play within `v0.10.0.rc3`..

AMS `0.9` is super old though, upgrade to `0.10` may still be an option.. Indeed, it brings some breaking changes but they are pretty light and I bet (well, I hope) most projects will not feel the difference )

**Comment by Bajena** [comment]
I agree with @stokarenko - adding support for lower versions would be too much work. I posted a PR to lock min version of AMS to 0.10.0.rc4: https://github.com/Bajena/ams_lazy_relationships/pull/60
